version: "3.7"

services:
  app:
    # name image
    image: 'countwords'    
    build:
      # path Dockerfile
      context: ./
      # Target use in dockerfile with multiple setup (example: local, prod)
      target: 'local'  
    ports:
      - 8000:8000    
    # One of the main advantages of using Docker volumes
    # is the possibility of changing the content/configuration
    # of a container without the need to recreate it.
    volumes:
     - ./src:/app/src
     - ./build:/app/build
